version: '3.7'

services:
  web:
    image: hoge_web
    container_name: hoge_web_container
    ports:
      - 80:80
    volumes:
      - ./volumes/web/log:/var/log/nginx
  web_api:
    image: hoge_web-api
    container_name: hoge_web-api_container
    environment:
      - REDIS_HOST
    ports:
      - 3000:3000
    volumes:
      - ./volumes/web_api/log:/var/log/express
    networks:
      - default
      - common_network
  redis:
    image: hoge_redis
    container_name: hoge_redis_container
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/data:/data
      - ./volumes/redis/log:/var/log/redis
networks:
  common_network:
    external: true
